permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: Yunlong Qi
  email: ylqi007@126.com
  link: http://ylqi007.github.io
  github: http://github.com/ylqi007

# 站点信息
title: ylqi007's blog
description: My personal blog
url: http://ylqi007.github.io
# rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/images_0.png
favicon: /public/img/images_0.png

# google analytics 设置
ga:
#  id: UA-54262064-1 
  url: http://ylqi007.github.io
  
# disqus 设置
disqus:
  shortname: xiaohan

# 主题设置，自动激活某个标签
active: DeepLearning

# 首页除了最新文章外显示分类
cates: 
  - Deep Learning

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档